### ISSUE TITLE
C - 修改字符串引起Bus Error？

### ISSUE THREAD

**Issue by oopsno** [SSSTA/issues#4]
编译运行这段程序

```
#include <stdio.h>

char * xp = "hentai";

int main() {
    xp[0] = 'H';
    printf("%s\n", xp);
    return 0;
}
```

程序没有输出，只得到了错误信息

``` shell
$ ./a.out
[1]    85312 bus error  ./a.out
```

环境是OS X 10.10.5，编译器是Apple LLVM version 7.0.0 (clang-700.0.72)。

Any idea? @tridays

**Comment by Draveness** [comment]
我可以 unwatch 么

**Comment by Qinka** [comment]
你们能说英文么。。。。。。

**Comment by Draveness** [comment]
No zuo no die

**Comment by Draveness** [comment]
We are not supposed to scare these newbies.

**Comment by oopsno** [comment]
你们这还让我怎么演示，都直播了

**Comment by Draveness** [comment]
删掉删掉
From Draveness
On 周日, 9月 27, 2015 at 10:36, SSSTA/issues
<reply@reply.github.com>
wrote:
你们这还让我怎么演示，都直播了

—
Reply to this email directly or view it on GitHub
[https://github.com/SSSTA/issues/issues/4#issuecomment-143513655] .[https://github.com/notifications/beacon/AGMUR0rP3OHrJa2SmaInXMo5DFVdlREXks5o1028gaJpZM4GEZ_-.gif]

**Comment by oopsno** [comment]
看到你转发的时候捎带了全文，我还是留着吧，顺便鼓吹一下邮件大法好←_←

**Comment by Draveness** [comment]
优秀的邮件大法

From Draveness
On 周日, 9月 27, 2015 at 10:46, SSSTA/issues
<reply@reply.github.com>
wrote:
看到你转发的时候捎带了全文，我还是留着吧，顺便鼓吹一下邮件大法好←_←

—
Reply to this email directly or view it on GitHub
[https://github.com/SSSTA/issues/issues/4#issuecomment-143513870] .[https://github.com/notifications/beacon/AGMUR9blMynmmaEG3QTKKcIAovOQZqXqks5o10_8gaJpZM4GEZ_-.gif]

**Comment by hsupu** [comment]
"hentai" 是字符串字面量，代表了一个字符串常量。常量的内容是拒绝被二次修改的。

**Comment by Qinka** [comment]
hentai怎么拉。。

**Comment by oopsno** [comment]
然而，用字符串字面值显式初始化数组时，比如

```
char XP[] = “Hentai”;
```

此时的`XP`是可<s>调教</s>修改的，确切的说，这种写法相当于

```
char XP[] = { ‘H’, ‘e’, ’n’, ’t’, ‘a’, ‘i’ };
```

然而，目测解释了详细原因，就真的没人来了~感兴趣请自行搜索『链接』『BSS段』『数据段』『堆栈』……
核能预警。

顺便，用显式初始化的数组是可以自动计算长度的，不过这特性好像又是个坑……

**Comment by oopsno** [comment]
然而，用字符串字面值显式初始化数组时，比如

``` C
char XP[] = "Hentai";
```

此时的`XP`是可<s>调教</s>修改的，确切的说，这种写法相当于

``` C
char XP[] = { 'H', 'e', 'n', 't', 'a', 'i', '\0' };
```

然而，目测解释了详细原因，就真的没人来了~感兴趣请自行搜索『链接』『BSS段』『数据段』『堆栈』……
核能预警。

顺便，用显式初始化的数组是可以自动计算长度的，不过这特性好像又是个坑……

**Comment by oopsno** [comment]
邮件发送的Markdown不能正确高亮是什么鬼...

**Comment by hsupu** [comment]
不是不能正确高亮，是你用了中文字符 “”‘’ 所以……

**Comment by oopsno** [comment]
What a Terrible Failure~

**Comment by ghost** [comment]
贵协的亡灵们
