### ISSUE TITLE
环境选择

### ISSUE THREAD

**Issue by pqsworld** [SSSTA/issues#6]
徐学长（变态）您好：
在观摩回味贵鞋的博大精深眼花缭乱乱七八糟的科普之后，我现在想到一个非常现实的问题。
您，或者你们介绍的那么多编程环境，我现在应该选哪个？
或者怎么选？
或者所有的都来一遍？！！

谢谢，15软工PQ

**Comment by pqsworld** [comment]
PS：仅指windows

**Comment by hsupu** [comment]
选择是要有依据的，根据你需求的不同你要选择不同的工具。
如何知道自己的需求？你可以广泛搜集信息以帮助自身决策。

另外，
不推荐所有的都经过尝试，但有好奇心的人应是不会听劝的。

这就是答案。

**Comment by hsupu** [comment]
问题未解决前就自行关闭……潘琪童鞋，你是觉得自己问的问题不需要回答么？

**Comment by pqsworld** [comment]
然而我

**Comment by pqsworld** [comment]
然而我以为close是over的意思~（return 0那种）
不熟悉受教道歉表示了解了-_-||

**Comment by hsupu** [comment]
没事……这个问题问的比较泛，你需要自己广泛搜集信息再重新决定问题的范围。
