### ISSUE TITLE
求助- -

### ISSUE THREAD

**Issue by Fancynice** [SSSTA/issues#8]
OJ题
输入三个字符（可以重复）后，按各字符的ASCII码从小到大的顺序输出这三个字符。

第一行输入一个数N,表示有N组测试数据。后面的N行输入多组数据，每组输入数据都是占一行，有三个字符组成，之间无空格。

对于每组输入数据，输出一行，字符中间用一个空格分开。

``` c
#include<stdio.h>
char paixu()
{
    char a[255];
    gets(a);
    char x,y,z;
    int i;
    if (a[0]>a[1])
    {
    x=a[0];
    a[0]=a[1];
    a[1]=x;
    }
    if(a[1]>a[2])
    {x=a[1];
    a[1]=a[2];
    a[2]=x;
    }
    if (a[0]>a[1])
    {
    x=a[0];
    a[0]=a[1];
    a[1]=x;
    }
   for(i=0;i<3;i++)
    printf("%c",a[i]);
    return 0;
}
int main()
{
    int i,j;
    i=0;
    printf("请输入次数\n");
    scanf("%d",&j);
    while(i<j+1)
    {
        paixu();
        i++;
    }
    return 0;
}
```

输入次数之后，一开始会莫名其妙输出一组字符。。什么原因啊。。

**Comment by oopsno** [comment]
如果是

> warning: this program uses gets(), which is unsafe.

字面意思。标准库手册有言：

> The gets() function does not perform bounds checking, therefore this function is extremely vulnerable to buffer-overflow attacks. It cannot be used safely (unless the program runs in an environment which restricts what can appear on stdin). For this reason, the function has been deprecated in the third corrigendum to the C99 standard and removed altogether in the C11 standard. fgets() and gets_s() are the recommended replacements.
> Never use gets().

**Never use gets(). fgets() and gets_s() are the recommended replacements.**
**Never use gets(). fgets() and gets_s() are the recommended replacements.**
**Never use gets(). fgets() and gets_s() are the recommended replacements.**

**然而，只有MSVC实现了gets_s，其他平台请绕行fgets**
**然而，只有MSVC实现了gets_s，其他平台请绕行fgets**
**然而，只有MSVC实现了gets_s，其他平台请绕行fgets**

如果看到了其他的，那么，先记住上面这段，然后我们来认真讨论下输入输出问题。

> 欢迎来到C语言中最污的输入输出部分。
> 然而这些东西实在太污了，你还是自己查吧，不然又有人说我半夜吓唬人了。
> 0. 在Unix下，标准输入输出(STDIN/STDOUT)都是行缓冲设备；
> 1. 按下回车的时候，确认一行，也添加一个`\n`（据说Windows下是`\n\r`?）
> 2. 各种读取函数在读标准输入输出的事后行为并不一致，有的处理换行，有的不处理

一言以蔽之，不会超时就`scanf`，人生苦短，何必浪费在花式格式化输入输出上。

A working C version:

``` C
#include <stdio.h>
#include <stdlib.h>

static char BUFFER[4];

static inline int compare(const void * a, const void * b) {
    return *((const char *) a) - *((const char *) b);
}

void magic()
{
    scanf("%s", BUFFER);
    qsort(BUFFER, 3, sizeof(char), compare);
    BUFFER[3] = 0;
    puts(BUFFER);
}

int main()
{
    int times;
    scanf("%d\n", &times);
    while(times --> 0) {
        magic();
    }
    return 0;
}
```

P.S. Why not just:

``` haskell
main = mapM_ putStrLn . map sort . tail . lines =<< getContents
```

这两段程序是等效的。
**Haskell大法好，Functional平安保。**

@tridays 抽空组织科普下吧，好像今年又把这点破事儿给忘了😀

**Comment by hsupu** [comment]
Windows下是`\r\n`回车换行。
`gets()`是一个不推荐使用的过时的函数，用`fgets()`代之为妙。

如博导所说，各种读取函数在读取时对`\n`的处理是不同的，尽量统一函数族用。

**Comment by ghost** [comment]
一言以蔽之，不会超时就scanf，人生苦短，何必浪费在花式格式化输入输出上。
小刘, 这特么不就是你的工作么? 还有, 你用个锤子半角中文标点.
